config/routes.rb
Rails.application.routes.draw do
  get 'users/:id',      to: 'users#show', as: 'user'
  post 'users', to: 'users#create', as: 'user_create'
  post 'mail', to: 'mail#route', as: 'mail'
  get 'splash', to: 'welcome#splash', as: 'splash'

  resources :listings

  root to: (ENV['ROOT_PAGE'] || 'welcome#index')

  resources :sessions, only: [:new, :create, :destroy, :show]
  get 'login', to: 'users#new', as: 'login'
  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'mission', to: 'mission#show', as: 'mission'

  
  get 'create_password_reset', to: 'users#create_password_reset', as: 'create_password_reset'
  get 'reset_password', to: 'users#reset_password', as: 'reset_password'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :listing_images
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  before_save :get_bay_area
  after_save :generate_temp_email
  validates_presence_of :subject
  validates_presence_of :body
  validates_presence_of :zip

  has_one :location, as: :locationeable

  INTENTIONS = [:buying, :selling, :lending, :trading, :borrowing]

  def get_bay_area
    ListingConcern::BAYS.each do |bay, zips|
      if zips.include?(zip)
        self.bay_area = bay 
        return true
      end
    end
    false
  end

  def generate_temp_email
    TempEmailAddress.find_or_create_by(listing_id: id, real_email_address: author.email)
  end

  def main_image_path
    if listing_images.any?
      listing_images.order(:precedence).first.image_path
    else
      "supplies.jpg"
    end
  end

  def has_image?
    @has_image ||= listing_images.any?
  end

  def location
    Location.find_by(locationeable_type: "Listing", locationeable_id: id) || author.location
  end

  def intensions
    Listing::INTENTIONS.select {|intention| self.send(intention)}
  end

  def temp_email_address
    TempEmailAddress.find_by(listing_id: self.id, real_email_address: author.preferred_email)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]
  # GET /listings
  # GET /listings.json
  def index
    @search = params[:search]
    @listings = Listing.where("body ILIKE ? or subject ILIKE ?" , "%#{@search}%", "%#{@search}%").where(active: true)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    @author = @listing.author
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @hash = {lend: false, borrow: false, steal: false, buy: false, sell: false}
  end

  # GET /listings/1/edit
  def edit
    # remove
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      ListingImage.create(precedence: 1, image_path: params[:listing][:listing_image][:image_path] , listing_id: @listing.id ) if params[:listing][:listing_image]
      redirect_to listing_path(@listing.id), notice: 'Listing was successfully created.'
    else
      flash.now[:notice] = @listing.errors.messages
      render "listings/new"
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:subject, :body, :buying, :selling, :lending, :trading, :borrowing, :zip).merge(author_id: current_user.id, active: true)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.number_field :author %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/_form.html.haml
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.number_field :author %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/edit.html.haml
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Type</th>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.author %></td>
        <td><%= listing.type %></td>
        <td><%= listing.subject %></td>
        <td><%= listing.body %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/index.html.haml
%section.search-form
  .container
    .row.search-mobile
      .col-md-8.col-sm-6.col-xs-12
        %form.form-inline
          .form-group.input-group
            %input.form-control{"aria-label" => "...", :placeholder => "Search", :type => "text"}
              .input-group-btn
                %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                  Location
                  %span.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} San Francisco
                  %li
                    %a{:href => "#"} East Bay
                  %li
                    %a{:href => "#"} North Bay
                  %li
                    %a{:href => "#"} South Bay
                  %li
                    %a{:href => "#"} Peninsula
                %button.btn.btn-search{:type => "submit"}
                  %i.fa.fa-search



    .recent-ads
      .row
        .list-ads.scrollit.flex-container
          .text-center
          - @listings.each do |listing|

            %li.list-item
              .list-content
                .caption
                  %h4.text-center This will be the listing Title
                - if listing.has_image?
                  = image_tag(listing.main_image_path, class: "img-responsive", height: "500px")
                - else
                  = image_tag(image_path(listing.main_image_path), class: "img-responsive", height: "500px")


  .col-md-4.map-fixed.fixed
    #googleMap{style: "width:100%;height:600px;"}

=content_for :javascript do
  = javascript_include_tag 'listings.js'

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/new.html.haml
.form-style-10
  / %form#user_preferences_form.disabled.form-style-10
  /   .section
  /     //%h3 You are logged in as #{current_user.nickname}
  /     %span> 1
  /     %h3 Account Details
  /   .inner-wrap
  /     %label.form-text-field
  /       Contact Name
  /       %input{:name => "name", :type => "text", value: "#{current_user.try('name') || ''}"}
  /     %label.form-text-field
  /       Email:
  /       %input{:name => "email", :type => "text", value: "#{current_user.try('email') || ''}"}
  /   .section
  /     %span> 2
  /     %h3 Preferred Contact Method:
  /   .inner-wrap
  /     %label.listing-checkbox{for: "text_button"}
  /       %input#text_button{type: 'radio', name: 'preferred_contact', value: 'text'}
  /         Text
  /     %label.listing-checkbox.form-text-field{for: "call_button"}
  /       %input#call_button{type: 'radio', name: 'preferred_contact', value: 'call'}
  /         Call
  /         %input#phone_box{:name => "phone", :type => "text", placeholder: 'phone number', value: "#{current_user.try('phone') || ''}"}
  /     %label.listing-checkbox.form-text-field{for: "email_button"}
  /       %input#email_button{type: 'radio', name: 'preferred_contact', value: 'email'}
  /         Email
  /         %input#email_box{:name => "email", :type => "text", placeholder: 'preferred email ', value: "#{current_user.try('email') || ''}"}
  /   .section
  /     %span> 3
  %h1 Create new listing
  .inner-wrap#create_listing_div
    = form_for @listing, url: url_for(controller: 'listings', action: "create"), html: { class: "create_listing_form directUpload", data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } } do |f|
      %label.form-text-field
        Title:
        = f.text_field :subject, id: "title_box", required: true
      %label.form-text-field
        I'd like to:
      %label.listing-checkbox{for: "lend_box"}
        = f.check_box :lending,   value: true, id: "lend_box",   name: "listing[lending]"
        Lend
      %label.listing-checkbox{for: "sell_box"}
        = f.check_box :selling,   value: true, id: "sell_box",   name: "listing[selling]"
        Sell
      %label.listing-checkbox{for: "buy_box"}
        = f.check_box :buying,    value: true, id: "buy_box",    name: "listing[buying]"
        Give Away
      / %label.listing-checkbox{for: "borrow_box"}
      /   = f.check_box :borrowing, value: true, id: "borrow_box", name: "listing[borrowing]"
      /   Borrow
      / %label.listing-checkbox{for: "trade_box"}
      /   = f.check_box :trading,   value: true, id: "trade_box",  name: "listing[trading]"
      /   Trade
      %label.form-text-field
        Zip Code:
        = f.text_field :zip, required: true

      %label.form-text-field
        Description:
        = f.text_area :body, required: true
      = f.fields_for :listing_image do |ff|
        %label.listing-photo
          Upload Photo:
          //= ff.label :image_path
          = ff.file_field :image_path
          = f.submit :submit, class: "btn btn-edswap", value: "Post Now"

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @listing.author %>
</p>

<p>
  <strong>Type:</strong>
  <%= @listing.type %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @listing.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @listing.body %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/listings/show.html.haml
%section.page-margins.text-center
  .row
    .col-md-6.col-sm-12
      %h2
        = @listing.subject
      %h4
        Posted by:
        = @author.name
      %p
        = "#{@listing.location.address}, #{@listing.location.city}"
      %h4
        Contact at:
        = "#{@listing.temp_email_address.temp_email_address}@edswap.org"
      %h2
        Information:
      %p
        = @listing.body
    .col-md-6.col-sm-12
      - if @listing.has_image?
        - @listing.listing_images.each do |image|
          = image_tag(image.image_path, width: "500px")
      - else
        = image_tag(image_path(@listing.main_image_path), class: "img-responsive", height: "500px")