config/routes.rb
Rails.application.routes.draw do
  get 'users/:id',      to: 'users#show', as: 'user'
  post 'users', to: 'users#create', as: 'user_create'
  post 'mail', to: 'mail#route', as: 'mail'
  get 'splash', to: 'welcome#splash', as: 'splash'

  resources :listings

  root to: (ENV['ROOT_PAGE'] || 'welcome#index')

  resources :sessions, only: [:new, :create, :destroy, :show]
  get 'login', to: 'users#new', as: 'login'
  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'mission', to: 'mission#show', as: 'mission'

  
  get 'create_password_reset', to: 'users#create_password_reset', as: 'create_password_reset'
  get 'reset_password', to: 'users#reset_password', as: 'reset_password'

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title edSwap
  %script{src: "http://maps.googleapis.com/maps/api/js"}
  = stylesheet_link_tag  'application', 'https://fonts.googleapis.com/css?family=Montserrat', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application'
  = yield :javascript
  %meta{name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0"}
  = csrf_meta_tags

%body
  %nav.navbar.navbar-fixed-top
    .container
      %a{href: "/listings"}
        =image_tag "edswap-logo.png", :height => "50"
      - if current_user
        / %a{href: "/users/#{current_user.id}", id: "nav_user_name"}
        /   %span Hi #{current_user.nickname}
      %ul.nav.navbar-right.nav-pills
        - if current_user
          %li
            = link_to user_path(session[:user_id]), class: "nav-text fa fa-user" do
              %span Hi #{current_user.nickname}
          %li
            = link_to new_listing_path, class: "nav-text fa fa-pencil-square-o" do
              %span New Listing
          %li
            = link_to mission_path, class: "nav-text fa fa-eye" do
              %span Mission

          %li
            = link_to signout_path, id: "sign_out", class: "nav-text fa fa-sign-out" do
              %span Sign Out
        - else
          %li
            = link_to login_path(destination_uri: new_listing_path), class: "nav-text fa fa-pencil-square-o" do
              %span New Listing
          %li
            = link_to mission_path, class: "nav-text fa fa-eye", title: "Mission" do
              %span Mission
          %li
            = link_to login_path, class: "nav-text  fa fa-sign-in" do
              %span Login
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield
%footer.container
  .row
    .col-md-4
    .col-md-4
      %ul.list-inline.social-buttons
        %li
          %a{:href => "https://twitter.com/edswap"}
            %i.fa.fa-twitter
        %li
          %a{:href => "https://www.facebook.com/EdSwap-1674834089452380/?fref=ts"}
            %i.fa.fa-facebook
        %li
          %a{:href => "mailto:info@edswap.org?Subject=Edswap%20Question"}
            %i.fa.fa-envelope
        %li
    .col-md-4.copyright
      %h6 Copyright &copy; edSwap 2015